/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PROYECTO;

import java.awt.Image;
import java.awt.MouseInfo;
import java.awt.Point;
import java.awt.Toolkit;
import java.awt.event.WindowAdapter;
import javax.swing.JOptionPane;

/**
 *
 * @author FerSotox
 */
public class PrincipalAdmin extends javax.swing.JFrame {

    /**
     * Creates new form Principal1
     */
    public PrincipalAdmin() {
        this.setUndecorated(true);
        initComponents();
        
     
        lblCedula.setVisible(false);
        txtCedula.setVisible(false);
        btnBuscarCliente.setVisible(false);
     
        lblServicio.setVisible(false);
        btnComputadora.setVisible(false);
        btnTelefono.setVisible(false);
        btnPresupuesto.setVisible(false);
        btnAcerca.setVisible(false);
        lblOpciones.setVisible(false);
        lblArchivo.setVisible(false);
        lblAnalisis.setVisible(false);
        
        
        btnInsumos.setVisible(false);
        btnNoReparados.setVisible(false);
        btnIngresos.setVisible(false);
        btnEgresos.setVisible(false);
        Warning.setVisible(false);
        btnArchivo.setBorderPainted(false);
        btnAnalisis.setBorderPainted(false);
        btnServicios.setBorderPainted(false);
        btnImpresora.setVisible(false);
        btnOpciones.setBorderPainted(false);
     
       
        
        lblConsultaCliente.setVisible(false);
       
  
        lblConsultaCliente.setVisible(false);
      
       
        btnCerrarSesion.setVisible(false);
        btnAyuda.setVisible(false);
        btnEstatus.setVisible(false);
        btnReporte.setBorderPainted(false);
        lblReporte.setVisible(false);
        btnContabilidad.setVisible(false);
        btnInventario.setVisible(false);
        lblConsultaUsuario.setVisible(false);
        lblCedulaUsuario.setVisible(false);
       
        txtCedulaUsuario.setVisible(false);
        
       
        btnBuscarUsuario.setVisible(false);
        btnMantenimiento.setVisible(false);
        
    }

    int x,y;
    
     @Override
   public Image getIconImage() {
        Image imagen = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("iconos/icono.png"));


        return imagen;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Minimizar = new javax.swing.JButton();
        Cerrar = new javax.swing.JButton();
        btnArchivo = new javax.swing.JButton();
        btnReporte = new javax.swing.JButton();
        btnOpciones = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnMantenimiento = new javax.swing.JButton();
        lblServicio = new javax.swing.JLabel();
        btnComputadora = new javax.swing.JButton();
        btnTelefono = new javax.swing.JButton();
        btnPresupuesto = new javax.swing.JButton();
        lblOpciones = new javax.swing.JLabel();
        lblReporte = new javax.swing.JLabel();
        btnInventario = new javax.swing.JButton();
        btnContabilidad = new javax.swing.JButton();
        Warning = new javax.swing.JLabel();
        btnNoReparados = new javax.swing.JButton();
        btnInsumos = new javax.swing.JButton();
        lblArchivo = new javax.swing.JLabel();
        btnBuscarCliente = new javax.swing.JButton();
        lblCedula = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        lblConsultaCliente = new javax.swing.JLabel();
        lblAnalisis = new javax.swing.JLabel();
        btnAyuda = new javax.swing.JButton();
        btnEstatus = new javax.swing.JButton();
        btnIngresos = new javax.swing.JButton();
        btnEgresos = new javax.swing.JButton();
        btnImpresora = new javax.swing.JButton();
        btnAcerca = new javax.swing.JButton();
        btnCerrarSesion = new javax.swing.JButton();
        lblCedulaUsuario = new javax.swing.JLabel();
        txtCedulaUsuario = new javax.swing.JTextField();
        lblConsultaUsuario = new javax.swing.JLabel();
        Brothernologic = new javax.swing.JLabel();
        Bandera = new javax.swing.JLabel();
        btnBuscarUsuario = new javax.swing.JButton();
        btnAnalisis = new javax.swing.JButton();
        Nombre = new javax.swing.JLabel();
        Administrador = new javax.swing.JLabel();
        btnServicios = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel1MouseEntered(evt);
            }
        });
        jPanel1.setLayout(null);

        Minimizar.setBackground(new java.awt.Color(255, 255, 255));
        Minimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Minimizar.png"))); // NOI18N
        Minimizar.setToolTipText("Minimizar");
        Minimizar.setBorderPainted(false);
        Minimizar.setContentAreaFilled(false);
        Minimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Minimizar.setFocusPainted(false);
        Minimizar.setFocusable(false);
        Minimizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MinimizarActionPerformed(evt);
            }
        });
        jPanel1.add(Minimizar);
        Minimizar.setBounds(730, 10, 30, 30);

        Cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Cerrar.png"))); // NOI18N
        Cerrar.setToolTipText("Cerrar");
        Cerrar.setBorderPainted(false);
        Cerrar.setContentAreaFilled(false);
        Cerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Cerrar.setFocusPainted(false);
        Cerrar.setFocusable(false);
        Cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerrarActionPerformed(evt);
            }
        });
        jPanel1.add(Cerrar);
        Cerrar.setBounds(760, 10, 30, 30);

        btnArchivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Archivo.png"))); // NOI18N
        btnArchivo.setToolTipText("Archivo");
        btnArchivo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 255), 2, true));
        btnArchivo.setContentAreaFilled(false);
        btnArchivo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnArchivo.setFocusPainted(false);
        btnArchivo.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Archivo_p.png"))); // NOI18N
        btnArchivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnArchivoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnArchivoMouseExited(evt);
            }
        });
        btnArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArchivoActionPerformed(evt);
            }
        });
        jPanel1.add(btnArchivo);
        btnArchivo.setBounds(10, 40, 140, 140);

        btnReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/ReportesPresupuestos.png"))); // NOI18N
        btnReporte.setToolTipText("Reportes");
        btnReporte.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 255), 2, true));
        btnReporte.setContentAreaFilled(false);
        btnReporte.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReporte.setFocusPainted(false);
        btnReporte.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/ReportesPresupuestos_p.png"))); // NOI18N
        btnReporte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnReporteMouseEntered(evt);
            }
        });
        btnReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteActionPerformed(evt);
            }
        });
        jPanel1.add(btnReporte);
        btnReporte.setBounds(10, 320, 140, 140);

        btnOpciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Opciones.png"))); // NOI18N
        btnOpciones.setToolTipText("Opciones");
        btnOpciones.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 255), 2, true));
        btnOpciones.setContentAreaFilled(false);
        btnOpciones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnOpciones.setFocusPainted(false);
        btnOpciones.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Opciones_p.png"))); // NOI18N
        btnOpciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnOpcionesMouseEntered(evt);
            }
        });
        btnOpciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpcionesActionPerformed(evt);
            }
        });
        jPanel1.add(btnOpciones);
        btnOpciones.setBounds(10, 600, 140, 140);

        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 255), 2, true));
        jPanel2.setFocusable(false);
        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMantenimiento.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnMantenimiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/mantenimiento.png"))); // NOI18N
        btnMantenimiento.setToolTipText("Mantenimiento");
        btnMantenimiento.setBorderPainted(false);
        btnMantenimiento.setContentAreaFilled(false);
        btnMantenimiento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMantenimiento.setFocusPainted(false);
        btnMantenimiento.setFocusable(false);
        btnMantenimiento.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/mantenimiento_p.png"))); // NOI18N
        btnMantenimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMantenimientoActionPerformed(evt);
            }
        });
        jPanel2.add(btnMantenimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 410, 150, 130));

        lblServicio.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        lblServicio.setForeground(new java.awt.Color(255, 255, 255));
        lblServicio.setText("Servicio");
        jPanel2.add(lblServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 140, 50));

        btnComputadora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/computadora.png"))); // NOI18N
        btnComputadora.setToolTipText("Computadora");
        btnComputadora.setBorderPainted(false);
        btnComputadora.setContentAreaFilled(false);
        btnComputadora.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnComputadora.setFocusPainted(false);
        btnComputadora.setFocusable(false);
        btnComputadora.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/computadora_p.png"))); // NOI18N
        btnComputadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComputadoraActionPerformed(evt);
            }
        });
        jPanel2.add(btnComputadora, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 140, 130));

        btnTelefono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Telefono.png"))); // NOI18N
        btnTelefono.setToolTipText("telefono");
        btnTelefono.setBorderPainted(false);
        btnTelefono.setContentAreaFilled(false);
        btnTelefono.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTelefono.setFocusPainted(false);
        btnTelefono.setFocusable(false);
        btnTelefono.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Telefono_p.png"))); // NOI18N
        btnTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTelefonoActionPerformed(evt);
            }
        });
        jPanel2.add(btnTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 200, 80, 120));

        btnPresupuesto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/ReportesPresupuestos.png"))); // NOI18N
        btnPresupuesto.setToolTipText("Presupuesto");
        btnPresupuesto.setBorderPainted(false);
        btnPresupuesto.setContentAreaFilled(false);
        btnPresupuesto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPresupuesto.setFocusPainted(false);
        btnPresupuesto.setFocusable(false);
        btnPresupuesto.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/ReportesPresupuestos_p.png"))); // NOI18N
        btnPresupuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPresupuestoActionPerformed(evt);
            }
        });
        jPanel2.add(btnPresupuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 410, 130, 120));

        lblOpciones.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        lblOpciones.setForeground(new java.awt.Color(255, 255, 255));
        lblOpciones.setText("Opciones");
        jPanel2.add(lblOpciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 190, -1));

        lblReporte.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        lblReporte.setForeground(new java.awt.Color(255, 255, 255));
        lblReporte.setText("Reportes");
        jPanel2.add(lblReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 190, -1));

        btnInventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/inventario.png"))); // NOI18N
        btnInventario.setToolTipText("Inventario");
        btnInventario.setBorderPainted(false);
        btnInventario.setContentAreaFilled(false);
        btnInventario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInventario.setFocusPainted(false);
        btnInventario.setFocusable(false);
        btnInventario.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/inventario_p.png"))); // NOI18N
        btnInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInventarioActionPerformed(evt);
            }
        });
        jPanel2.add(btnInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, -1, -1));

        btnContabilidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/contabilidad.png"))); // NOI18N
        btnContabilidad.setToolTipText("Contabilidad");
        btnContabilidad.setBorderPainted(false);
        btnContabilidad.setContentAreaFilled(false);
        btnContabilidad.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnContabilidad.setFocusPainted(false);
        btnContabilidad.setFocusable(false);
        btnContabilidad.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/contabilidad_p.png"))); // NOI18N
        btnContabilidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContabilidadActionPerformed(evt);
            }
        });
        jPanel2.add(btnContabilidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 410, 140, 140));

        Warning.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/cancelar.png"))); // NOI18N
        Warning.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(Warning, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 260, 80, 80));

        btnNoReparados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Telefono.png"))); // NOI18N
        btnNoReparados.setToolTipText("Equipos No Reparados");
        btnNoReparados.setBorderPainted(false);
        btnNoReparados.setContentAreaFilled(false);
        btnNoReparados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNoReparados.setFocusPainted(false);
        btnNoReparados.setFocusable(false);
        btnNoReparados.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Telefono_p.png"))); // NOI18N
        btnNoReparados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNoReparadosActionPerformed(evt);
            }
        });
        jPanel2.add(btnNoReparados, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, 120, 130));

        btnInsumos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/insumos.png"))); // NOI18N
        btnInsumos.setToolTipText("Insumos");
        btnInsumos.setBorderPainted(false);
        btnInsumos.setContentAreaFilled(false);
        btnInsumos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInsumos.setFocusPainted(false);
        btnInsumos.setFocusable(false);
        btnInsumos.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/insumos_p.png"))); // NOI18N
        btnInsumos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsumosActionPerformed(evt);
            }
        });
        jPanel2.add(btnInsumos, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 410, 130, 120));

        lblArchivo.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        lblArchivo.setForeground(new java.awt.Color(255, 255, 255));
        lblArchivo.setText("Archivo");
        jPanel2.add(lblArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 190, -1));

        btnBuscarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Buscar.png"))); // NOI18N
        btnBuscarCliente.setToolTipText("Buscar");
        btnBuscarCliente.setBorderPainted(false);
        btnBuscarCliente.setContentAreaFilled(false);
        btnBuscarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscarCliente.setFocusPainted(false);
        btnBuscarCliente.setFocusable(false);
        btnBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarClienteActionPerformed(evt);
            }
        });
        jPanel2.add(btnBuscarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, 60, 60));

        lblCedula.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblCedula.setForeground(new java.awt.Color(204, 204, 204));
        lblCedula.setText("Cedula del Cliente");
        lblCedula.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                lblCedulaComponentHidden(evt);
            }
        });
        jPanel2.add(lblCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 170, 30));

        txtCedula.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtCedula.setToolTipText("");
        jPanel2.add(txtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 250, 40));

        lblConsultaCliente.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblConsultaCliente.setForeground(new java.awt.Color(204, 204, 204));
        lblConsultaCliente.setText("Consulta de Cliente");
        lblConsultaCliente.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                lblConsultaClienteComponentHidden(evt);
            }
        });
        jPanel2.add(lblConsultaCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 220, 30));

        lblAnalisis.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        lblAnalisis.setForeground(new java.awt.Color(255, 255, 255));
        lblAnalisis.setText("Analisis");
        jPanel2.add(lblAnalisis, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 190, -1));

        btnAyuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Ayuda.png"))); // NOI18N
        btnAyuda.setToolTipText("Ayuda");
        btnAyuda.setBorderPainted(false);
        btnAyuda.setContentAreaFilled(false);
        btnAyuda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAyuda.setFocusPainted(false);
        btnAyuda.setFocusable(false);
        btnAyuda.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Ayuda_p.png"))); // NOI18N
        btnAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAyudaActionPerformed(evt);
            }
        });
        jPanel2.add(btnAyuda, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, 140, 130));

        btnEstatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/estatus.png"))); // NOI18N
        btnEstatus.setToolTipText("Estatus Servicio");
        btnEstatus.setBorderPainted(false);
        btnEstatus.setContentAreaFilled(false);
        btnEstatus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEstatus.setFocusPainted(false);
        btnEstatus.setFocusable(false);
        btnEstatus.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/estatus_p.png"))); // NOI18N
        btnEstatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstatusActionPerformed(evt);
            }
        });
        jPanel2.add(btnEstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 400, 140, 140));

        btnIngresos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/ingreso.png"))); // NOI18N
        btnIngresos.setToolTipText("Ingresos");
        btnIngresos.setBorderPainted(false);
        btnIngresos.setContentAreaFilled(false);
        btnIngresos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIngresos.setFocusPainted(false);
        btnIngresos.setFocusable(false);
        btnIngresos.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/ingreso_p.png"))); // NOI18N
        btnIngresos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresosActionPerformed(evt);
            }
        });
        jPanel2.add(btnIngresos, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, -1, -1));

        btnEgresos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/egreso.png"))); // NOI18N
        btnEgresos.setToolTipText("Egresos");
        btnEgresos.setBorderPainted(false);
        btnEgresos.setContentAreaFilled(false);
        btnEgresos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEgresos.setFocusPainted(false);
        btnEgresos.setFocusable(false);
        btnEgresos.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/egreso_p.png"))); // NOI18N
        btnEgresos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEgresosActionPerformed(evt);
            }
        });
        jPanel2.add(btnEgresos, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, 140, 140));

        btnImpresora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Impresora.png"))); // NOI18N
        btnImpresora.setToolTipText("Impresora");
        btnImpresora.setBorderPainted(false);
        btnImpresora.setContentAreaFilled(false);
        btnImpresora.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnImpresora.setFocusPainted(false);
        btnImpresora.setFocusable(false);
        btnImpresora.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Impresora_p.png"))); // NOI18N
        btnImpresora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImpresoraActionPerformed(evt);
            }
        });
        jPanel2.add(btnImpresora, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 130, 130));

        btnAcerca.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnAcerca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Acercade.png"))); // NOI18N
        btnAcerca.setToolTipText("Acerca de");
        btnAcerca.setBorderPainted(false);
        btnAcerca.setContentAreaFilled(false);
        btnAcerca.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAcerca.setFocusPainted(false);
        btnAcerca.setFocusable(false);
        btnAcerca.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Acercade_p.png"))); // NOI18N
        btnAcerca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcercaActionPerformed(evt);
            }
        });
        jPanel2.add(btnAcerca, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 410, 150, 130));

        btnCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/cambiarusuario.png"))); // NOI18N
        btnCerrarSesion.setToolTipText("Cerrar sesión");
        btnCerrarSesion.setBorderPainted(false);
        btnCerrarSesion.setContentAreaFilled(false);
        btnCerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCerrarSesion.setFocusPainted(false);
        btnCerrarSesion.setFocusable(false);
        btnCerrarSesion.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/cambiarusuario_p.png"))); // NOI18N
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });
        jPanel2.add(btnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 160, 140));

        lblCedulaUsuario.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblCedulaUsuario.setForeground(new java.awt.Color(204, 204, 204));
        lblCedulaUsuario.setText("Cedula del Usuario");
        lblCedulaUsuario.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                lblCedulaUsuarioComponentHidden(evt);
            }
        });
        jPanel2.add(lblCedulaUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 490, 170, 30));

        txtCedulaUsuario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtCedulaUsuario.setToolTipText("");
        jPanel2.add(txtCedulaUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 530, 250, 40));

        lblConsultaUsuario.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblConsultaUsuario.setForeground(new java.awt.Color(204, 204, 204));
        lblConsultaUsuario.setText("Consulta de Usuario");
        lblConsultaUsuario.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                lblConsultaUsuarioComponentHidden(evt);
            }
        });
        jPanel2.add(lblConsultaUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, 220, 30));

        Brothernologic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Imagen1.png"))); // NOI18N
        jPanel2.add(Brothernologic, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, 380, 60));

        Bandera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/bandera-italiana.png"))); // NOI18N
        jPanel2.add(Bandera, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 250, 170));

        btnBuscarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Buscar.png"))); // NOI18N
        btnBuscarUsuario.setToolTipText("Buscar");
        btnBuscarUsuario.setBorderPainted(false);
        btnBuscarUsuario.setContentAreaFilled(false);
        btnBuscarUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscarUsuario.setFocusPainted(false);
        btnBuscarUsuario.setFocusable(false);
        btnBuscarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarUsuarioActionPerformed(evt);
            }
        });
        jPanel2.add(btnBuscarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 520, 60, 60));

        jPanel1.add(jPanel2);
        jPanel2.setBounds(150, 40, 640, 700);

        btnAnalisis.setForeground(new java.awt.Color(153, 255, 255));
        btnAnalisis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Analisis1.png"))); // NOI18N
        btnAnalisis.setToolTipText("Analisis");
        btnAnalisis.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 255), 2, true));
        btnAnalisis.setContentAreaFilled(false);
        btnAnalisis.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAnalisis.setFocusPainted(false);
        btnAnalisis.setFocusable(false);
        btnAnalisis.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Analisis1_p.png"))); // NOI18N
        btnAnalisis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnalisisActionPerformed(evt);
            }
        });
        jPanel1.add(btnAnalisis);
        btnAnalisis.setBounds(10, 460, 140, 140);

        Nombre.setFont(new java.awt.Font("Thames", 3, 18)); // NOI18N
        Nombre.setForeground(new java.awt.Color(255, 255, 255));
        Nombre.setText("Control Brothernologic V 1.3");
        jPanel1.add(Nombre);
        Nombre.setBounds(20, 10, 230, 20);

        Administrador.setFont(new java.awt.Font("Thames", 1, 14)); // NOI18N
        Administrador.setForeground(new java.awt.Color(255, 255, 255));
        Administrador.setText("Administrador");
        jPanel1.add(Administrador);
        Administrador.setBounds(620, 20, 100, 20);

        btnServicios.setForeground(new java.awt.Color(153, 255, 255));
        btnServicios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/servicios.png"))); // NOI18N
        btnServicios.setToolTipText("Servicios");
        btnServicios.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 255), 2, true));
        btnServicios.setContentAreaFilled(false);
        btnServicios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnServicios.setFocusPainted(false);
        btnServicios.setFocusable(false);
        btnServicios.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/servicios_p.png"))); // NOI18N
        btnServicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnServiciosActionPerformed(evt);
            }
        });
        jPanel1.add(btnServicios);
        btnServicios.setBounds(10, 180, 140, 140);

        Fondo.setBackground(new java.awt.Color(204, 204, 204));
        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/20FB742C2.jpg"))); // NOI18N
        Fondo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                FondoMouseDragged(evt);
            }
        });
        Fondo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                FondoMousePressed(evt);
            }
        });
        Fondo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                FondoKeyPressed(evt);
            }
        });
        jPanel1.add(Fondo);
        Fondo.setBounds(0, 0, 800, 750);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MinimizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MinimizarActionPerformed

        setExtendedState(ICONIFIED);
    }//GEN-LAST:event_MinimizarActionPerformed

    private void CerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarActionPerformed

        ConfirmarSalir confir=new ConfirmarSalir();

        confir.setResizable(false);
        confir.setLocationRelativeTo(null);
        confir.setVisible(true);

    }//GEN-LAST:event_CerrarActionPerformed

    private void btnArchivoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnArchivoMouseEntered

    }//GEN-LAST:event_btnArchivoMouseEntered

    private void btnArchivoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnArchivoMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnArchivoMouseExited

    private void btnArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArchivoActionPerformed
        lblCedula.setVisible(true);
        txtCedula.setVisible(true);
        btnBuscarCliente.setVisible(true);
  
        lblServicio.setVisible(false);
        btnComputadora.setVisible(false);
        btnTelefono.setVisible(false);
        btnPresupuesto.setVisible(false);
        btnAcerca.setVisible(false);
        lblOpciones.setVisible(false);
        lblArchivo.setVisible(true);
        lblAnalisis.setVisible(false);
       
        btnImpresora.setVisible(false);
        btnInsumos.setVisible(false);
        btnNoReparados.setVisible(false);
        btnIngresos.setVisible(false);
        btnEgresos.setVisible(false);
        Warning.setVisible(false);
        btnArchivo.setBorderPainted(true);
        btnAnalisis.setBorderPainted(false);
        btnServicios.setBorderPainted(false);
        btnOpciones.setBorderPainted(false);
        Bandera.setVisible(false);
        Brothernologic.setVisible(false);

        lblConsultaCliente.setVisible(true);
     
        btnCerrarSesion.setVisible(false);
        btnAyuda.setVisible(false);
        btnEstatus.setVisible(false);
        btnReporte.setBorderPainted(false);
        lblReporte.setVisible(false);
        btnContabilidad.setVisible(false);
        btnInventario.setVisible(false);
        lblConsultaUsuario.setVisible(true);
        lblCedulaUsuario.setVisible(true);
       
        txtCedulaUsuario.setVisible(true);
   
        btnBuscarUsuario.setVisible(true);
        btnMantenimiento.setVisible(false);
        
    }//GEN-LAST:event_btnArchivoActionPerformed

    private void btnReporteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReporteMouseEntered

    }//GEN-LAST:event_btnReporteMouseEntered

    private void btnReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteActionPerformed
        lblCedula.setVisible(false);
        txtCedula.setVisible(false);
       
        btnBuscarCliente.setVisible(false);
      
        lblServicio.setVisible(false);
        btnComputadora.setVisible(false);
        btnTelefono.setVisible(false);
        btnPresupuesto.setVisible(false);
        btnAcerca.setVisible(false);
        lblOpciones.setVisible(false);
        lblArchivo.setVisible(false);
        lblAnalisis.setVisible(false);
       
        btnImpresora.setVisible(false);
        btnInsumos.setVisible(false);
        btnNoReparados.setVisible(true);
        btnIngresos.setVisible(false);
        btnEgresos.setVisible(false);
        Warning.setVisible(true);
        btnArchivo.setBorderPainted(false);
        btnAnalisis.setBorderPainted(false);
        btnServicios.setBorderPainted(false);
        btnOpciones.setBorderPainted(false);
        Bandera.setVisible(false);
        Brothernologic.setVisible(false);
      
        lblConsultaCliente.setVisible(false);
      
      
        btnCerrarSesion.setVisible(false);
        btnAyuda.setVisible(false);
        btnEstatus.setVisible(false);
        btnReporte.setBorderPainted(true);
        lblReporte.setVisible(true);
        btnContabilidad.setVisible(true);
        btnInventario.setVisible(true);
        lblConsultaUsuario.setVisible(false);
        lblCedulaUsuario.setVisible(false);
       
        txtCedulaUsuario.setVisible(false);
        
       
         btnBuscarUsuario.setVisible(false);
         btnMantenimiento.setVisible(false);
       
    }//GEN-LAST:event_btnReporteActionPerformed

    private void btnOpcionesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOpcionesMouseEntered

    }//GEN-LAST:event_btnOpcionesMouseEntered

    private void btnOpcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpcionesActionPerformed
        lblCedula.setVisible(false);
        txtCedula.setVisible(false);
        btnBuscarCliente.setVisible(false);
       
        lblServicio.setVisible(false);
        btnComputadora.setVisible(false);
        btnTelefono.setVisible(false);
        btnPresupuesto.setVisible(false);
        btnAcerca.setVisible(true);
        lblOpciones.setVisible(true);
        lblAnalisis.setVisible(false);
        lblArchivo.setVisible(false);
       
        btnImpresora.setVisible(false);
        btnInsumos.setVisible(false);
        btnNoReparados.setVisible(false);
        btnIngresos.setVisible(false);
        btnEgresos.setVisible(false);
        Warning.setVisible(false);
        btnArchivo.setBorderPainted(false);
        btnAnalisis.setBorderPainted(false);
        btnServicios.setBorderPainted(false);
        btnOpciones.setBorderPainted(true);
        Bandera.setVisible(false);
        Brothernologic.setVisible(false);
        
      
        lblConsultaCliente.setVisible(false);
       
       
         btnCerrarSesion.setVisible(true);
        btnAyuda.setVisible(true);
        btnEstatus.setVisible(false);
        btnReporte.setBorderPainted(false);
        lblReporte.setVisible(false);
        btnContabilidad.setVisible(false);
        btnInventario.setVisible(false);
        lblConsultaUsuario.setVisible(false);
        lblCedulaUsuario.setVisible(false);
        
        txtCedulaUsuario.setVisible(false);
       
      
         btnBuscarUsuario.setVisible(false);
         btnMantenimiento.setVisible(true);
    }//GEN-LAST:event_btnOpcionesActionPerformed

    private void btnComputadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComputadoraActionPerformed

        Computadora co=new Computadora();

        co.setResizable(false);
        co.setLocationRelativeTo(null);
        co.setVisible(true);

    }//GEN-LAST:event_btnComputadoraActionPerformed

    private void btnTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTelefonoActionPerformed
        Telefono tele=new Telefono();

        tele.setResizable(false);
        tele.setLocationRelativeTo(null);
        tele.setVisible(true); // TODO add your handling code here:
    }//GEN-LAST:event_btnTelefonoActionPerformed

    private void btnPresupuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPresupuestoActionPerformed

        Presupuesto pre=new Presupuesto();

        pre.setResizable(false);
        pre.setLocationRelativeTo(null);
        pre.setVisible(true);

    }//GEN-LAST:event_btnPresupuestoActionPerformed

    private void btnInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventarioActionPerformed

        Inventario inv=new Inventario();
        inv.setResizable(false);
        inv.setLocationRelativeTo(inv);
        inv.setVisible(true);

    }//GEN-LAST:event_btnInventarioActionPerformed

    private void btnContabilidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContabilidadActionPerformed
        Contabilidad conta=new Contabilidad();
        conta.setResizable(false);
        conta.setLocationRelativeTo(null);
        conta.setVisible(true);

    }//GEN-LAST:event_btnContabilidadActionPerformed

    private void btnNoReparadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNoReparadosActionPerformed
        NoReparados NoRe=new NoReparados();
        NoRe.setResizable(false);
        NoRe.setLocationRelativeTo(null);
        NoRe.setVisible(true);
    }//GEN-LAST:event_btnNoReparadosActionPerformed

    private void btnInsumosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsumosActionPerformed

        Insumos insu=new Insumos();
        insu.setResizable(false);
        insu.setLocationRelativeTo(null);
        insu.setVisible(true);

    }//GEN-LAST:event_btnInsumosActionPerformed

    private void btnAnalisisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnalisisActionPerformed
         lblCedula.setVisible(false);
        txtCedula.setVisible(false);
        btnBuscarCliente.setVisible(false);
       
        lblServicio.setVisible(false);
        btnComputadora.setVisible(false);
        btnTelefono.setVisible(false);
        btnPresupuesto.setVisible(false);
        btnAcerca.setVisible(false);
        lblOpciones.setVisible(false);
        lblArchivo.setVisible(false);
        lblAnalisis.setVisible(true);
        
        btnImpresora.setVisible(false);
        btnInsumos.setVisible(true);
        btnNoReparados.setVisible(false);
        btnIngresos.setVisible(true);
        btnEgresos.setVisible(true);
        Warning.setVisible(false);
        btnArchivo.setBorderPainted(false);
        btnAnalisis.setBorderPainted(true);
        btnServicios.setBorderPainted(false);
        btnOpciones.setBorderPainted(false);
        Bandera.setVisible(false);
        Brothernologic.setVisible(false);
       
        lblConsultaCliente.setVisible(false);
    
       
        btnCerrarSesion.setVisible(false);
        btnAyuda.setVisible(false);
        btnEstatus.setVisible(true);
        btnReporte.setBorderPainted(false);
        lblReporte.setVisible(false);
        btnContabilidad.setVisible(false);
        btnInventario.setVisible(false);
        lblConsultaUsuario.setVisible(false);
        lblCedulaUsuario.setVisible(false);
        
        txtCedulaUsuario.setVisible(false);
        
                btnBuscarUsuario.setVisible(false);
         btnMantenimiento.setVisible(false);
    }//GEN-LAST:event_btnAnalisisActionPerformed

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed

       
           Inicio i=new Inicio();

        i.setResizable(false);
        i.setLocationRelativeTo(null);
        i.setVisible(true);
        dispose();
       

    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void FondoMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FondoMouseDragged

        Point point = MouseInfo.getPointerInfo().getLocation() ;
        setLocation(point.x - x, point.y - y )  ;
    }//GEN-LAST:event_FondoMouseDragged

    private void FondoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FondoMousePressed

        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_FondoMousePressed

    private void FondoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FondoKeyPressed

    }//GEN-LAST:event_FondoKeyPressed

    private void jPanel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1MouseEntered

    private void btnServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnServiciosActionPerformed
      lblCedula.setVisible(false);
        txtCedula.setVisible(false);
        btnBuscarCliente.setVisible(false);
    
        lblServicio.setVisible(true);
        btnComputadora.setVisible(true);
        btnTelefono.setVisible(true);
        btnPresupuesto.setVisible(true);
        btnAcerca.setVisible(false);
        lblOpciones.setVisible(false);
        lblArchivo.setVisible(false);
        lblAnalisis.setVisible(false);
      
        btnImpresora.setVisible(true);
        btnInsumos.setVisible(false);
        btnNoReparados.setVisible(false);
        btnIngresos.setVisible(false);
        btnEgresos.setVisible(false);
        Warning.setVisible(false);
        btnArchivo.setBorderPainted(false);
        btnAnalisis.setBorderPainted(false);
        btnServicios.setBorderPainted(true);
        btnOpciones.setBorderPainted(false);
        Bandera.setVisible(false);
        Brothernologic.setVisible(false);
       
        
       
        lblConsultaCliente.setVisible(false);
     
     
         btnCerrarSesion.setVisible(false);
        btnAyuda.setVisible(false);
        btnEstatus.setVisible(false);
        btnReporte.setBorderPainted(false);
lblReporte.setVisible(false);
btnContabilidad.setVisible(false);
        btnInventario.setVisible(false);
lblConsultaUsuario.setVisible(false);
        lblCedulaUsuario.setVisible(false);
       
        txtCedulaUsuario.setVisible(false);
       
 btnBuscarUsuario.setVisible(false);
btnMantenimiento.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_btnServiciosActionPerformed

    private void btnBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarClienteActionPerformed
       
        if(txtCedula.getText().equals("1234")){
          
        ConsultaCliente cocli=new ConsultaCliente();
        cocli.setVisible(true);
        txtCedula.setText("");
        }
        else{
         txtCedula.setText("");  
           int regis= JOptionPane.showConfirmDialog(null, "Cliente no registrado ¿desea registrarlo?");
                    if(regis==JOptionPane.YES_OPTION){
           
             
         NuevoCliente reg=new NuevoCliente();
      reg.setLocationRelativeTo(reg);
       reg.setResizable(false);
      reg.setVisible(true);
       
        }}
    }//GEN-LAST:event_btnBuscarClienteActionPerformed

    private void lblCedulaComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_lblCedulaComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_lblCedulaComponentHidden

    private void lblConsultaClienteComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_lblConsultaClienteComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_lblConsultaClienteComponentHidden

    private void btnAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAyudaActionPerformed
    try {
              Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler " + "src\\MANUAL\\MANUAL.pdf");
    } catch (Exception e){
      JOptionPane.showMessageDialog(rootPane, "Error al Abrir el Archivo", "ERROR", JOptionPane.ERROR_MESSAGE);  
    }
    }//GEN-LAST:event_btnAyudaActionPerformed

    private void btnEstatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstatusActionPerformed
        Estatus es=new Estatus();

        es.setResizable(false);
        es.setLocationRelativeTo(null);
        es.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_btnEstatusActionPerformed

    private void btnIngresosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresosActionPerformed
Ingresos in=new Ingresos();
                
        in.setResizable(false);
        in.setLocationRelativeTo(null);
        in.setVisible(true);
    }//GEN-LAST:event_btnIngresosActionPerformed

    private void btnEgresosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEgresosActionPerformed
Egresos egr=new Egresos();
                
        egr.setResizable(false);
        egr.setLocationRelativeTo(null);
        egr.setVisible(true);
    }//GEN-LAST:event_btnEgresosActionPerformed

    private void btnImpresoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImpresoraActionPerformed
        Impresora im=new Impresora();
                
        im.setResizable(false);
        im.setLocationRelativeTo(null);
        im.setVisible(true);
    }//GEN-LAST:event_btnImpresoraActionPerformed

    private void btnAcercaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcercaActionPerformed
        AcercaDe ad=new AcercaDe();

        ad.setResizable(false);
        ad.setLocationRelativeTo(null);
        ad.setVisible(true);
    }//GEN-LAST:event_btnAcercaActionPerformed

    private void lblCedulaUsuarioComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_lblCedulaUsuarioComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_lblCedulaUsuarioComponentHidden

    private void lblConsultaUsuarioComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_lblConsultaUsuarioComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_lblConsultaUsuarioComponentHidden

    private void btnBuscarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarUsuarioActionPerformed
         if(txtCedulaUsuario.getText().equals("1234")){
            ConsultarUsuario cu=new ConsultarUsuario();
            txtCedulaUsuario.setText("");
            cu.setResizable(false);
            cu.setLocationRelativeTo(null);
            cu.setVisible(true);
        }
        else{
            
            int option=JOptionPane.showConfirmDialog(null,"usuario no registrado ¿desea agregar usuraio? ");
            if(option==JOptionPane.YES_OPTION){
              AgregarUsuario ag=new AgregarUsuario();
              txtCedulaUsuario.setText("");
            ag.setResizable(false);
            ag.setLocationRelativeTo(null);
            ag.setVisible(true);  
            }
        }
    }//GEN-LAST:event_btnBuscarUsuarioActionPerformed

    private void btnMantenimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMantenimientoActionPerformed
        
        Mantenimiento man=new Mantenimiento();
        man.setResizable(false);
        man.setLocationRelativeTo(null);
        man.setVisible(true);
    }//GEN-LAST:event_btnMantenimientoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Administrador;
    private javax.swing.JLabel Bandera;
    private javax.swing.JLabel Brothernologic;
    private javax.swing.JButton Cerrar;
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton Minimizar;
    private javax.swing.JLabel Nombre;
    private javax.swing.JLabel Warning;
    private javax.swing.JButton btnAcerca;
    private javax.swing.JButton btnAnalisis;
    private javax.swing.JButton btnArchivo;
    private javax.swing.JButton btnAyuda;
    private javax.swing.JButton btnBuscarCliente;
    private javax.swing.JButton btnBuscarUsuario;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnComputadora;
    private javax.swing.JButton btnContabilidad;
    private javax.swing.JButton btnEgresos;
    private javax.swing.JButton btnEstatus;
    private javax.swing.JButton btnImpresora;
    private javax.swing.JButton btnIngresos;
    private javax.swing.JButton btnInsumos;
    private javax.swing.JButton btnInventario;
    private javax.swing.JButton btnMantenimiento;
    private javax.swing.JButton btnNoReparados;
    private javax.swing.JButton btnOpciones;
    private javax.swing.JButton btnPresupuesto;
    private javax.swing.JButton btnReporte;
    private javax.swing.JButton btnServicios;
    private javax.swing.JButton btnTelefono;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblAnalisis;
    private javax.swing.JLabel lblArchivo;
    private javax.swing.JLabel lblCedula;
    private javax.swing.JLabel lblCedulaUsuario;
    private javax.swing.JLabel lblConsultaCliente;
    private javax.swing.JLabel lblConsultaUsuario;
    private javax.swing.JLabel lblOpciones;
    private javax.swing.JLabel lblReporte;
    private javax.swing.JLabel lblServicio;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtCedulaUsuario;
    // End of variables declaration//GEN-END:variables
}
