/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PROYECTO;

import java.awt.Image;
import java.awt.MouseInfo;
import java.awt.Point;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author FerSotox
 */
public class PrincipalUser extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalUser
     */
    public PrincipalUser() {this.setUndecorated(true);
        initComponents();
        lblCedula.setVisible(false);
        txtCedula.setVisible(false);
        btnBuscar.setVisible(false);
        btnAgregar.setVisible(false);
        lblServicio.setVisible(false);
        btnComputadora.setVisible(false);
        btnTelefono.setVisible(false);
        btnPresupuesto.setVisible(false);
        btnAcerca.setVisible(false);
        lblOpciones.setVisible(false);
        lblArchivo.setVisible(false);
        lblAnalisis.setVisible(false);
        lblNombre.setVisible(false);
        btnOK.setVisible(false);
        btnImpresora.setVisible(false);
        btnInsumos.setVisible(false);
        btnNoReparados.setVisible(false);
        btnIngresos.setVisible(false);
        btnEgresos.setVisible(false);
        Warning.setVisible(false);
        btnArchivo.setBorderPainted(false);
        btnAnalisis.setBorderPainted(false);
        btnServicios.setBorderPainted(false);
        btnOpciones.setBorderPainted(false);
        txtCodRecibo.setVisible(false);
        lblCodRecibo.setVisible(false);
        btnIrFactura.setVisible(false);
        btnAceptarCod.setVisible(false);
        lblConsultaCliente.setVisible(false);
        lblConsultaRecibo.setVisible(false);
        btnBuscarRecibo.setVisible(false);
        lblConsultaCliente.setVisible(false);
        lblConsultaRecibo.setVisible(false);
        lblEstadoRecibo.setVisible(false);
        btnCerrarSesion.setVisible(false);
        btnAyuda.setVisible(false);
        btnEstatus.setVisible(false);
    }

    int x,y;
    
    
    
    
     @Override
   public Image getIconImage() {
        Image imagen = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("iconos/icono.png"));


        return imagen;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Minimizar = new javax.swing.JButton();
        Cerrar = new javax.swing.JButton();
        btnArchivo = new javax.swing.JButton();
        btnAnalisis = new javax.swing.JButton();
        btnOpciones = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblServicio = new javax.swing.JLabel();
        btnComputadora = new javax.swing.JButton();
        btnTelefono = new javax.swing.JButton();
        btnPresupuesto = new javax.swing.JButton();
        txtCedula = new javax.swing.JTextField();
        lblCedula = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        btnAcerca = new javax.swing.JButton();
        lblOpciones = new javax.swing.JLabel();
        lblAnalisis = new javax.swing.JLabel();
        lblArchivo = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        btnOK = new javax.swing.JButton();
        btnImpresora = new javax.swing.JButton();
        btnIngresos = new javax.swing.JButton();
        btnEgresos = new javax.swing.JButton();
        Warning = new javax.swing.JLabel();
        btnNoReparados = new javax.swing.JButton();
        btnInsumos = new javax.swing.JButton();
        Brothernologic = new javax.swing.JLabel();
        Bandera = new javax.swing.JLabel();
        lblConsultaCliente = new javax.swing.JLabel();
        lblConsultaRecibo = new javax.swing.JLabel();
        txtCodRecibo = new javax.swing.JTextField();
        lblCodRecibo = new javax.swing.JLabel();
        btnBuscarRecibo = new javax.swing.JButton();
        lblEstadoRecibo = new javax.swing.JLabel();
        btnAceptarCod = new javax.swing.JButton();
        btnIrFactura = new javax.swing.JButton();
        btnAyuda = new javax.swing.JButton();
        btnCerrarSesion = new javax.swing.JButton();
        btnEstatus = new javax.swing.JButton();
        btnServicios = new javax.swing.JButton();
        Nombre = new javax.swing.JLabel();
        Usuario = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel1MouseEntered(evt);
            }
        });
        jPanel1.setLayout(null);

        Minimizar.setBackground(new java.awt.Color(255, 255, 255));
        Minimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Minimizar.png"))); // NOI18N
        Minimizar.setToolTipText("Minimizar");
        Minimizar.setBorderPainted(false);
        Minimizar.setContentAreaFilled(false);
        Minimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Minimizar.setFocusPainted(false);
        Minimizar.setFocusable(false);
        Minimizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MinimizarActionPerformed(evt);
            }
        });
        jPanel1.add(Minimizar);
        Minimizar.setBounds(730, 10, 30, 30);

        Cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Cerrar.png"))); // NOI18N
        Cerrar.setToolTipText("Cerrar");
        Cerrar.setBorderPainted(false);
        Cerrar.setContentAreaFilled(false);
        Cerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Cerrar.setFocusPainted(false);
        Cerrar.setFocusable(false);
        Cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerrarActionPerformed(evt);
            }
        });
        jPanel1.add(Cerrar);
        Cerrar.setBounds(760, 10, 30, 30);

        btnArchivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Archivo.png"))); // NOI18N
        btnArchivo.setToolTipText("Archivo");
        btnArchivo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 255), 2, true));
        btnArchivo.setContentAreaFilled(false);
        btnArchivo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnArchivo.setFocusPainted(false);
        btnArchivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnArchivoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnArchivoMouseExited(evt);
            }
        });
        btnArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArchivoActionPerformed(evt);
            }
        });
        jPanel1.add(btnArchivo);
        btnArchivo.setBounds(10, 40, 140, 140);

        btnAnalisis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Analisis1.png"))); // NOI18N
        btnAnalisis.setToolTipText("Analisis");
        btnAnalisis.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 255), 2, true));
        btnAnalisis.setContentAreaFilled(false);
        btnAnalisis.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAnalisis.setFocusPainted(false);
        btnAnalisis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAnalisisMouseEntered(evt);
            }
        });
        btnAnalisis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnalisisActionPerformed(evt);
            }
        });
        jPanel1.add(btnAnalisis);
        btnAnalisis.setBounds(10, 320, 140, 140);

        btnOpciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Opciones.png"))); // NOI18N
        btnOpciones.setToolTipText("Opciones");
        btnOpciones.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 255), 2, true));
        btnOpciones.setContentAreaFilled(false);
        btnOpciones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnOpciones.setFocusPainted(false);
        btnOpciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnOpcionesMouseEntered(evt);
            }
        });
        btnOpciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpcionesActionPerformed(evt);
            }
        });
        jPanel1.add(btnOpciones);
        btnOpciones.setBounds(10, 460, 140, 140);

        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 255), 2, true));
        jPanel2.setFocusable(false);
        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblServicio.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        lblServicio.setForeground(new java.awt.Color(255, 255, 255));
        lblServicio.setText("Servicio");
        jPanel2.add(lblServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 140, 50));

        btnComputadora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/computadora.png"))); // NOI18N
        btnComputadora.setToolTipText("Computadora");
        btnComputadora.setBorderPainted(false);
        btnComputadora.setContentAreaFilled(false);
        btnComputadora.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnComputadora.setFocusPainted(false);
        btnComputadora.setFocusable(false);
        btnComputadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComputadoraActionPerformed(evt);
            }
        });
        jPanel2.add(btnComputadora, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 140, 130));

        btnTelefono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Telefono.png"))); // NOI18N
        btnTelefono.setToolTipText("telefono");
        btnTelefono.setBorderPainted(false);
        btnTelefono.setContentAreaFilled(false);
        btnTelefono.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTelefono.setFocusPainted(false);
        btnTelefono.setFocusable(false);
        btnTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTelefonoActionPerformed(evt);
            }
        });
        jPanel2.add(btnTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, 110, 130));

        btnPresupuesto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/ReportesPresupuestos.png"))); // NOI18N
        btnPresupuesto.setToolTipText("Presupuesto");
        btnPresupuesto.setBorderPainted(false);
        btnPresupuesto.setContentAreaFilled(false);
        btnPresupuesto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPresupuesto.setFocusPainted(false);
        btnPresupuesto.setFocusable(false);
        btnPresupuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPresupuestoActionPerformed(evt);
            }
        });
        jPanel2.add(btnPresupuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 330, 130, 130));

        txtCedula.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtCedula.setToolTipText("");
        jPanel2.add(txtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 250, 40));

        lblCedula.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblCedula.setForeground(new java.awt.Color(204, 204, 204));
        lblCedula.setText("Cedula del Cliente");
        lblCedula.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                lblCedulaComponentHidden(evt);
            }
        });
        jPanel2.add(lblCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 170, 30));

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Buscar.png"))); // NOI18N
        btnBuscar.setToolTipText("Buscar");
        btnBuscar.setBorderPainted(false);
        btnBuscar.setContentAreaFilled(false);
        btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscar.setFocusPainted(false);
        btnBuscar.setFocusable(false);
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel2.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, 60, 60));

        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Agregar.png"))); // NOI18N
        btnAgregar.setToolTipText("Agregar");
        btnAgregar.setBorderPainted(false);
        btnAgregar.setContentAreaFilled(false);
        btnAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregar.setFocusPainted(false);
        btnAgregar.setFocusable(false);
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel2.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 250, 60, 60));

        btnAcerca.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnAcerca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Acercade.png"))); // NOI18N
        btnAcerca.setToolTipText("Acerca de");
        btnAcerca.setBorderPainted(false);
        btnAcerca.setContentAreaFilled(false);
        btnAcerca.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAcerca.setFocusPainted(false);
        btnAcerca.setFocusable(false);
        btnAcerca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcercaActionPerformed(evt);
            }
        });
        jPanel2.add(btnAcerca, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, 140, 120));

        lblOpciones.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        lblOpciones.setForeground(new java.awt.Color(255, 255, 255));
        lblOpciones.setText("Opciones");
        jPanel2.add(lblOpciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 190, -1));

        lblAnalisis.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        lblAnalisis.setForeground(new java.awt.Color(255, 255, 255));
        lblAnalisis.setText("Analisis");
        jPanel2.add(lblAnalisis, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 190, -1));

        lblArchivo.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        lblArchivo.setForeground(new java.awt.Color(255, 255, 255));
        lblArchivo.setText("Archivo");
        jPanel2.add(lblArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 190, -1));

        lblNombre.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre.setText("                     ");
        jPanel2.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 330, 30));

        btnOK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Seleccionar.png"))); // NOI18N
        btnOK.setToolTipText("Aceptar");
        btnOK.setBorderPainted(false);
        btnOK.setContentAreaFilled(false);
        btnOK.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnOK.setFocusPainted(false);
        btnOK.setFocusable(false);
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });
        jPanel2.add(btnOK, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, 60, 50));

        btnImpresora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Impresora.png"))); // NOI18N
        btnImpresora.setToolTipText("Impresora");
        btnImpresora.setBorderPainted(false);
        btnImpresora.setContentAreaFilled(false);
        btnImpresora.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnImpresora.setFocusPainted(false);
        btnImpresora.setFocusable(false);
        btnImpresora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImpresoraActionPerformed(evt);
            }
        });
        jPanel2.add(btnImpresora, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, 130, 130));

        btnIngresos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/ingreso.png"))); // NOI18N
        btnIngresos.setToolTipText("Ingresos");
        btnIngresos.setBorderPainted(false);
        btnIngresos.setContentAreaFilled(false);
        btnIngresos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIngresos.setFocusPainted(false);
        btnIngresos.setFocusable(false);
        btnIngresos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresosActionPerformed(evt);
            }
        });
        jPanel2.add(btnIngresos, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

        btnEgresos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/egreso.png"))); // NOI18N
        btnEgresos.setToolTipText("Egresos");
        btnEgresos.setBorderPainted(false);
        btnEgresos.setContentAreaFilled(false);
        btnEgresos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEgresos.setFocusPainted(false);
        btnEgresos.setFocusable(false);
        btnEgresos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEgresosActionPerformed(evt);
            }
        });
        jPanel2.add(btnEgresos, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 140, 140));

        Warning.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/cancelar.png"))); // NOI18N
        Warning.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(Warning, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 420, 80, 80));

        btnNoReparados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Telefono.png"))); // NOI18N
        btnNoReparados.setToolTipText("Equipos No Reparados");
        btnNoReparados.setBorderPainted(false);
        btnNoReparados.setContentAreaFilled(false);
        btnNoReparados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNoReparados.setFocusPainted(false);
        btnNoReparados.setFocusable(false);
        btnNoReparados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNoReparadosActionPerformed(evt);
            }
        });
        jPanel2.add(btnNoReparados, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 350, 120, 130));

        btnInsumos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/insumos.png"))); // NOI18N
        btnInsumos.setToolTipText("Insumos");
        btnInsumos.setBorderPainted(false);
        btnInsumos.setContentAreaFilled(false);
        btnInsumos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInsumos.setFocusPainted(false);
        btnInsumos.setFocusable(false);
        btnInsumos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsumosActionPerformed(evt);
            }
        });
        jPanel2.add(btnInsumos, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 390, 130, 120));

        Brothernologic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Imagen1.png"))); // NOI18N
        jPanel2.add(Brothernologic, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 380, 90));

        Bandera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/bandera-italiana.png"))); // NOI18N
        jPanel2.add(Bandera, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 260, 170));

        lblConsultaCliente.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblConsultaCliente.setForeground(new java.awt.Color(204, 204, 204));
        lblConsultaCliente.setText("Consulta de Cliente");
        lblConsultaCliente.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                lblConsultaClienteComponentHidden(evt);
            }
        });
        jPanel2.add(lblConsultaCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 220, 30));

        lblConsultaRecibo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblConsultaRecibo.setForeground(new java.awt.Color(204, 204, 204));
        lblConsultaRecibo.setText("Consulta de Recibo");
        lblConsultaRecibo.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                lblConsultaReciboComponentHidden(evt);
            }
        });
        jPanel2.add(lblConsultaRecibo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 220, 30));

        txtCodRecibo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtCodRecibo.setToolTipText("");
        jPanel2.add(txtCodRecibo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 430, 250, 40));

        lblCodRecibo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblCodRecibo.setForeground(new java.awt.Color(204, 204, 204));
        lblCodRecibo.setText("Codigo de Recibo");
        lblCodRecibo.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                lblCodReciboComponentHidden(evt);
            }
        });
        jPanel2.add(lblCodRecibo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, 170, 30));

        btnBuscarRecibo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Buscar.png"))); // NOI18N
        btnBuscarRecibo.setToolTipText("Buscar");
        btnBuscarRecibo.setBorderPainted(false);
        btnBuscarRecibo.setContentAreaFilled(false);
        btnBuscarRecibo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscarRecibo.setFocusPainted(false);
        btnBuscarRecibo.setFocusable(false);
        btnBuscarRecibo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarReciboActionPerformed(evt);
            }
        });
        jPanel2.add(btnBuscarRecibo, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 420, 60, 60));

        lblEstadoRecibo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblEstadoRecibo.setForeground(new java.awt.Color(255, 255, 255));
        lblEstadoRecibo.setText("                     ");
        jPanel2.add(lblEstadoRecibo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 490, 270, 30));

        btnAceptarCod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Seleccionar.png"))); // NOI18N
        btnAceptarCod.setToolTipText("Aceptar");
        btnAceptarCod.setBorderPainted(false);
        btnAceptarCod.setContentAreaFilled(false);
        btnAceptarCod.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAceptarCod.setFocusPainted(false);
        btnAceptarCod.setFocusable(false);
        btnAceptarCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarCodActionPerformed(evt);
            }
        });
        jPanel2.add(btnAceptarCod, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 480, 60, 50));

        btnIrFactura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Seleccionar.png"))); // NOI18N
        btnIrFactura.setToolTipText("Aceptar");
        btnIrFactura.setBorderPainted(false);
        btnIrFactura.setContentAreaFilled(false);
        btnIrFactura.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIrFactura.setFocusPainted(false);
        btnIrFactura.setFocusable(false);
        btnIrFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIrFacturaActionPerformed(evt);
            }
        });
        jPanel2.add(btnIrFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 480, 60, 50));

        btnAyuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Ayuda.png"))); // NOI18N
        btnAyuda.setToolTipText("Ayuda");
        btnAyuda.setBorderPainted(false);
        btnAyuda.setContentAreaFilled(false);
        btnAyuda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAyuda.setFocusPainted(false);
        btnAyuda.setFocusable(false);
        btnAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAyudaActionPerformed(evt);
            }
        });
        jPanel2.add(btnAyuda, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, 140, 130));

        btnCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/cambiarusuario.png"))); // NOI18N
        btnCerrarSesion.setToolTipText("Cerrar sesión");
        btnCerrarSesion.setBorderPainted(false);
        btnCerrarSesion.setContentAreaFilled(false);
        btnCerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCerrarSesion.setFocusPainted(false);
        btnCerrarSesion.setFocusable(false);
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });
        jPanel2.add(btnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 140, 130));

        btnEstatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/estatus.png"))); // NOI18N
        btnEstatus.setToolTipText("Estatus Servicio");
        btnEstatus.setBorderPainted(false);
        btnEstatus.setContentAreaFilled(false);
        btnEstatus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEstatus.setFocusPainted(false);
        btnEstatus.setFocusable(false);
        btnEstatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstatusActionPerformed(evt);
            }
        });
        jPanel2.add(btnEstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 170, 140, 140));

        jPanel1.add(jPanel2);
        jPanel2.setBounds(150, 40, 640, 560);

        btnServicios.setForeground(new java.awt.Color(153, 255, 255));
        btnServicios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/servicios.png"))); // NOI18N
        btnServicios.setToolTipText("Servicios");
        btnServicios.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 255), 2, true));
        btnServicios.setContentAreaFilled(false);
        btnServicios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnServicios.setFocusPainted(false);
        btnServicios.setFocusable(false);
        btnServicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnServiciosActionPerformed(evt);
            }
        });
        jPanel1.add(btnServicios);
        btnServicios.setBounds(10, 180, 140, 140);

        Nombre.setFont(new java.awt.Font("Thames", 3, 18)); // NOI18N
        Nombre.setForeground(new java.awt.Color(255, 255, 255));
        Nombre.setText("Control Brothernologic V 1.3");
        jPanel1.add(Nombre);
        Nombre.setBounds(10, 10, 230, 20);

        Usuario.setFont(new java.awt.Font("Thames", 1, 14)); // NOI18N
        Usuario.setForeground(new java.awt.Color(255, 255, 255));
        Usuario.setText("Usuario");
        jPanel1.add(Usuario);
        Usuario.setBounds(660, 20, 60, 20);

        Fondo.setBackground(new java.awt.Color(204, 204, 204));
        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/20FB742C2.jpg"))); // NOI18N
        Fondo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                FondoMouseDragged(evt);
            }
        });
        Fondo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                FondoMousePressed(evt);
            }
        });
        Fondo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                FondoKeyPressed(evt);
            }
        });
        jPanel1.add(Fondo);
        Fondo.setBounds(0, 0, 800, 610);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MinimizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MinimizarActionPerformed

        setExtendedState(ICONIFIED);
    }//GEN-LAST:event_MinimizarActionPerformed

    private void CerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarActionPerformed

        ConfirmarSalir confir=new ConfirmarSalir();

        confir.setResizable(false);
        confir.setLocationRelativeTo(null);
        confir.setVisible(true);
    }//GEN-LAST:event_CerrarActionPerformed

    private void btnArchivoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnArchivoMouseEntered

    }//GEN-LAST:event_btnArchivoMouseEntered

    private void btnArchivoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnArchivoMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnArchivoMouseExited

    private void btnArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArchivoActionPerformed
        lblCedula.setVisible(true);
        txtCedula.setVisible(true);
        btnBuscar.setVisible(true);
        btnAgregar.setVisible(false);
        lblServicio.setVisible(false);
        btnComputadora.setVisible(false);
        btnTelefono.setVisible(false);
        btnPresupuesto.setVisible(false);
        btnAcerca.setVisible(false);
        lblOpciones.setVisible(false);
        lblArchivo.setVisible(true);
        lblAnalisis.setVisible(false);
        lblNombre.setVisible(false);
        btnOK.setVisible(false);
        btnImpresora.setVisible(false);
        btnInsumos.setVisible(false);
        btnNoReparados.setVisible(false);
        btnIngresos.setVisible(false);
        btnEgresos.setVisible(false);
        Warning.setVisible(false);
        btnArchivo.setBorderPainted(true);
        btnAnalisis.setBorderPainted(false);
        btnServicios.setBorderPainted(false);
        btnOpciones.setBorderPainted(false);
        Bandera.setVisible(false);
        Brothernologic.setVisible(false);
        txtCodRecibo.setVisible(true);
        lblCodRecibo.setVisible(true);
        btnBuscarRecibo.setVisible(true);
        lblConsultaCliente.setVisible(true);
        lblConsultaRecibo.setVisible(true);
        btnCerrarSesion.setVisible(false);
        btnAyuda.setVisible(false);
        btnEstatus.setVisible(false);
       
    }//GEN-LAST:event_btnArchivoActionPerformed

    private void btnAnalisisMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAnalisisMouseEntered

    }//GEN-LAST:event_btnAnalisisMouseEntered

    private void btnAnalisisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnalisisActionPerformed
        lblCedula.setVisible(false);
        txtCedula.setVisible(false);
        btnBuscar.setVisible(false);
        btnAgregar.setVisible(false);
        lblServicio.setVisible(false);
        btnComputadora.setVisible(false);
        btnTelefono.setVisible(false);
        btnPresupuesto.setVisible(false);
        btnAcerca.setVisible(false);
        lblOpciones.setVisible(false);
        lblArchivo.setVisible(false);
        lblAnalisis.setVisible(true);
        lblNombre.setVisible(false);
        btnOK.setVisible(false);
        btnImpresora.setVisible(false);
        btnInsumos.setVisible(true);
        btnNoReparados.setVisible(true);
        btnIngresos.setVisible(true);
        btnEgresos.setVisible(true);
        Warning.setVisible(true);
        btnArchivo.setBorderPainted(false);
        btnAnalisis.setBorderPainted(true);
        btnServicios.setBorderPainted(false);
        btnOpciones.setBorderPainted(false);
        Bandera.setVisible(false);
        Brothernologic.setVisible(false);
        txtCodRecibo.setVisible(false);
        lblCodRecibo.setVisible(false);
        btnIrFactura.setVisible(false);
        btnAceptarCod.setVisible(false);
        btnBuscarRecibo.setVisible(false);
        lblConsultaCliente.setVisible(false);
        lblConsultaRecibo.setVisible(false);
        lblEstadoRecibo.setVisible(false);
        btnCerrarSesion.setVisible(false);
        btnAyuda.setVisible(false);
        btnEstatus.setVisible(true);
    }//GEN-LAST:event_btnAnalisisActionPerformed

    private void btnOpcionesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOpcionesMouseEntered

    }//GEN-LAST:event_btnOpcionesMouseEntered

    private void btnOpcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpcionesActionPerformed
        lblCedula.setVisible(false);
        txtCedula.setVisible(false);
        btnBuscar.setVisible(false);
        btnAgregar.setVisible(false);
        lblServicio.setVisible(false);
        btnComputadora.setVisible(false);
        btnTelefono.setVisible(false);
        btnPresupuesto.setVisible(false);
        btnAcerca.setVisible(true);
        lblOpciones.setVisible(true);
        lblAnalisis.setVisible(false);
        lblArchivo.setVisible(false);
        lblNombre.setVisible(false);
        btnOK.setVisible(false);
        btnImpresora.setVisible(false);
        btnInsumos.setVisible(false);
        btnNoReparados.setVisible(false);
        btnIngresos.setVisible(false);
        btnEgresos.setVisible(false);
        Warning.setVisible(false);
        btnArchivo.setBorderPainted(false);
        btnAnalisis.setBorderPainted(false);
        btnServicios.setBorderPainted(false);
        btnOpciones.setBorderPainted(true);
        Bandera.setVisible(false);
        Brothernologic.setVisible(false);
        txtCodRecibo.setVisible(false);
        lblCodRecibo.setVisible(false);
        btnIrFactura.setVisible(false);
        btnBuscarRecibo.setVisible(false);
        btnAceptarCod.setVisible(false);
        lblConsultaCliente.setVisible(false);
        lblConsultaRecibo.setVisible(false);
         lblEstadoRecibo.setVisible(false);
         btnCerrarSesion.setVisible(true);
        btnAyuda.setVisible(true);
        btnEstatus.setVisible(false);
    }//GEN-LAST:event_btnOpcionesActionPerformed

    private void btnComputadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComputadoraActionPerformed

        Computadora co=new Computadora();

        co.setResizable(false);
        co.setLocationRelativeTo(null);
        co.setVisible(true);
    }//GEN-LAST:event_btnComputadoraActionPerformed

    private void btnTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTelefonoActionPerformed
        Telefono tele=new Telefono();

        tele.setResizable(false);
        tele.setLocationRelativeTo(null);
        tele.setVisible(true); // TODO add your handling code here:
    }//GEN-LAST:event_btnTelefonoActionPerformed

    private void btnPresupuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPresupuestoActionPerformed

        Presupuesto pre=new Presupuesto();

        pre.setResizable(false);
        pre.setLocationRelativeTo(null);
        pre.setVisible(true);
    }//GEN-LAST:event_btnPresupuestoActionPerformed

    private void lblCedulaComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_lblCedulaComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_lblCedulaComponentHidden

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        if(txtCedula.getText().equals("1234")){
            lblNombre.setVisible(true);
            btnOK.setVisible(true);
            lblNombre.setText("Nombre Usuario");
        }
        else{
            lblNombre.setVisible(true);
           lblNombre.setText("Usuario No registrado");
           btnAgregar.setVisible(true);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        
        
        NuevoCliente nvo=new NuevoCliente();

        nvo.setResizable(false);
        nvo.setLocationRelativeTo(null);
        nvo.setVisible(true);
        
         lblCedula.setVisible(false);
        txtCedula.setVisible(false);
        txtCedula.setText("");
        btnBuscar.setVisible(false);
        btnAgregar.setVisible(false);
        lblServicio.setVisible(false);
        btnComputadora.setVisible(false);
        btnTelefono.setVisible(false);
        btnPresupuesto.setVisible(false);
        btnAcerca.setVisible(false);
        lblOpciones.setVisible(false);
        lblArchivo.setVisible(false);
        lblAnalisis.setVisible(false);
        lblNombre.setVisible(false);
        btnOK.setVisible(false);
        btnImpresora.setVisible(false);
        btnInsumos.setVisible(false);
        btnNoReparados.setVisible(false);
        btnIngresos.setVisible(false);
        btnEgresos.setVisible(false);
        Warning.setVisible(false);
        btnArchivo.setBorderPainted(false);
        btnAnalisis.setBorderPainted(false);
        btnServicios.setBorderPainted(false);
        btnOpciones.setBorderPainted(false); 
        Bandera.setVisible(true);
        Brothernologic.setVisible(true);
        txtCodRecibo.setVisible(false);
        lblCodRecibo.setVisible(false);
        btnIrFactura.setVisible(false);
        btnAceptarCod.setVisible(false);
        btnBuscarRecibo.setVisible(false);
        lblConsultaCliente.setVisible(false);
        lblConsultaRecibo.setVisible(false);
         lblEstadoRecibo.setVisible(false);
         btnCerrarSesion.setVisible(false);
        btnAyuda.setVisible(false);
        btnEstatus.setVisible(false);
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnAcercaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcercaActionPerformed
        AcercaDe ad=new AcercaDe();

        ad.setResizable(false);
        ad.setLocationRelativeTo(null);
        ad.setVisible(true);

    }//GEN-LAST:event_btnAcercaActionPerformed

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
      lblCedula.setVisible(false);
        txtCedula.setVisible(false);
        txtCedula.setText("");
        btnBuscar.setVisible(false);
        btnAgregar.setVisible(false);
        lblServicio.setVisible(false);
        btnComputadora.setVisible(false);
        btnTelefono.setVisible(false);
        btnPresupuesto.setVisible(false);
        btnAcerca.setVisible(false);
        lblOpciones.setVisible(false);
        lblArchivo.setVisible(false);
        lblAnalisis.setVisible(false);
        lblNombre.setVisible(false);
        btnOK.setVisible(false);
        btnImpresora.setVisible(false);
        btnInsumos.setVisible(false);
        btnNoReparados.setVisible(false);
        btnIngresos.setVisible(false);
        btnEgresos.setVisible(false);
        Warning.setVisible(false);
        btnArchivo.setBorderPainted(false);
        btnAnalisis.setBorderPainted(false);
        btnServicios.setBorderPainted(false);
        btnOpciones.setBorderPainted(false); 
        Bandera.setVisible(true);
        Brothernologic.setVisible(true);
        txtCodRecibo.setVisible(false);
        lblCodRecibo.setVisible(false);
        btnIrFactura.setVisible(false);
        btnAceptarCod.setVisible(false);
        btnBuscarRecibo.setVisible(false);
        lblConsultaCliente.setVisible(false);
        lblConsultaRecibo.setVisible(false);
         lblEstadoRecibo.setVisible(false);
         btnCerrarSesion.setVisible(false);
        btnAyuda.setVisible(false);
        btnEstatus.setVisible(false);
    }//GEN-LAST:event_btnOKActionPerformed

    private void btnImpresoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImpresoraActionPerformed
        Impresora im=new Impresora();
                
        im.setResizable(false);
        im.setLocationRelativeTo(null);
        im.setVisible(true);
    }//GEN-LAST:event_btnImpresoraActionPerformed

    private void btnIngresosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresosActionPerformed
        Ingresos in=new Ingresos();
                
        in.setResizable(false);
        in.setLocationRelativeTo(null);
        in.setVisible(true);
       
    }//GEN-LAST:event_btnIngresosActionPerformed

    private void btnEgresosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEgresosActionPerformed
       Egresos egr=new Egresos();
                
        egr.setResizable(false);
        egr.setLocationRelativeTo(null);
        egr.setVisible(true);
       
    }//GEN-LAST:event_btnEgresosActionPerformed

    private void btnNoReparadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNoReparadosActionPerformed
        NoReparados NoRe=new NoReparados();
        NoRe.setResizable(false);
        NoRe.setLocationRelativeTo(null);
        NoRe.setVisible(true);
    }//GEN-LAST:event_btnNoReparadosActionPerformed

    private void btnInsumosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsumosActionPerformed

        Insumos insu=new Insumos();
        insu.setResizable(false);
        insu.setLocationRelativeTo(null);
        insu.setVisible(true);
    }//GEN-LAST:event_btnInsumosActionPerformed

    private void btnServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnServiciosActionPerformed
        lblCedula.setVisible(false);
        txtCedula.setVisible(false);
        btnBuscar.setVisible(false);
        btnAgregar.setVisible(false);
        lblServicio.setVisible(true);
        btnComputadora.setVisible(true);
        btnTelefono.setVisible(true);
        btnPresupuesto.setVisible(true);
        btnAcerca.setVisible(false);
        lblOpciones.setVisible(false);
        lblArchivo.setVisible(false);
        lblAnalisis.setVisible(false);
        lblNombre.setVisible(false);
        btnOK.setVisible(false);
        btnImpresora.setVisible(true);
        btnInsumos.setVisible(false);
        btnNoReparados.setVisible(false);
        btnIngresos.setVisible(false);
        btnEgresos.setVisible(false);
        Warning.setVisible(false);
        btnArchivo.setBorderPainted(false);
        btnAnalisis.setBorderPainted(false);
        btnServicios.setBorderPainted(true);
        btnOpciones.setBorderPainted(false);
        Bandera.setVisible(false);
        Brothernologic.setVisible(false);
        txtCodRecibo.setVisible(false);
        lblCodRecibo.setVisible(false);
        btnBuscarRecibo.setVisible(false);
        btnIrFactura.setVisible(false);
        btnAceptarCod.setVisible(false);
        lblConsultaCliente.setVisible(false);
        lblConsultaRecibo.setVisible(false);
         lblEstadoRecibo.setVisible(false);
         btnCerrarSesion.setVisible(false);
        btnAyuda.setVisible(false);
        btnEstatus.setVisible(false);
    }//GEN-LAST:event_btnServiciosActionPerformed

    private void btnAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAyudaActionPerformed
try {
              Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler " + "src\\MANUAL\\MANUAL.pdf");
    } catch (Exception e){
      JOptionPane.showMessageDialog(rootPane, "Error al Abrir el Archivo", "ERROR", JOptionPane.ERROR_MESSAGE);  
    }
        
    }//GEN-LAST:event_btnAyudaActionPerformed

    private void FondoMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FondoMouseDragged

        Point point = MouseInfo.getPointerInfo().getLocation() ;
        setLocation(point.x - x, point.y - y )  ;
    }//GEN-LAST:event_FondoMouseDragged

    private void FondoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FondoMousePressed

        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_FondoMousePressed

    private void FondoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FondoKeyPressed

    }//GEN-LAST:event_FondoKeyPressed

    private void jPanel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1MouseEntered

    private void lblConsultaClienteComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_lblConsultaClienteComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_lblConsultaClienteComponentHidden

    private void lblConsultaReciboComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_lblConsultaReciboComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_lblConsultaReciboComponentHidden

    private void lblCodReciboComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_lblCodReciboComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_lblCodReciboComponentHidden

    private void btnBuscarReciboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarReciboActionPerformed
        if(txtCodRecibo.getText().equals("001")){
            lblEstadoRecibo.setVisible(true);
            btnIrFactura.setVisible(true);
            btnAceptarCod.setVisible(false);
            lblEstadoRecibo.setText("Servicio Realizado");
        }
        if(txtCodRecibo.getText().equals("002")){
           lblEstadoRecibo.setVisible(true);
           lblEstadoRecibo.setText("Servicio No Realizado");
           btnAceptarCod.setVisible(true);
           btnIrFactura.setVisible(false);
        }
        if(txtCodRecibo.getText().equals("")){
            lblEstadoRecibo.setVisible(true);
           lblEstadoRecibo.setText("Error (recibo no encontrado)");
           btnAceptarCod.setVisible(true);
           btnIrFactura.setVisible(false);
        }
    }//GEN-LAST:event_btnBuscarReciboActionPerformed

    private void btnAceptarCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarCodActionPerformed
       lblCedula.setVisible(false);
        txtCedula.setVisible(false);
        txtCedula.setText("");
        btnBuscar.setVisible(false);
        btnAgregar.setVisible(false);
        lblServicio.setVisible(false);
        btnComputadora.setVisible(false);
        btnTelefono.setVisible(false);
        btnPresupuesto.setVisible(false);
        btnAcerca.setVisible(false);
        lblOpciones.setVisible(false);
        lblArchivo.setVisible(false);
        lblAnalisis.setVisible(false);
        lblNombre.setVisible(false);
        btnOK.setVisible(false);
        btnImpresora.setVisible(false);
        btnInsumos.setVisible(false);
        btnNoReparados.setVisible(false);
        btnIngresos.setVisible(false);
        btnEgresos.setVisible(false);
        Warning.setVisible(false);
        btnArchivo.setBorderPainted(false);
        btnAnalisis.setBorderPainted(false);
        btnServicios.setBorderPainted(false);
        btnOpciones.setBorderPainted(false); 
        Bandera.setVisible(true);
        Brothernologic.setVisible(true);
        txtCodRecibo.setVisible(false);
        lblCodRecibo.setVisible(false);
        btnIrFactura.setVisible(false);
        btnAceptarCod.setVisible(false);
        btnBuscarRecibo.setVisible(false);
        lblConsultaCliente.setVisible(false);
        lblConsultaRecibo.setVisible(false);
        lblEstadoRecibo.setVisible(false);
        btnCerrarSesion.setVisible(false);
        btnAyuda.setVisible(false);
        btnEstatus.setVisible(false);
    }//GEN-LAST:event_btnAceptarCodActionPerformed

    private void btnIrFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIrFacturaActionPerformed
        Factura c=new Factura();
        c.setResizable(false);
        c.setLocationRelativeTo(null);
        c.setVisible(true);
        lblCedula.setVisible(false);
        txtCedula.setVisible(false);
        txtCedula.setText("");
        btnBuscar.setVisible(false);
        btnAgregar.setVisible(false);
        lblServicio.setVisible(false);
        btnComputadora.setVisible(false);
        btnTelefono.setVisible(false);
        btnPresupuesto.setVisible(false);
        btnAcerca.setVisible(false);
        lblOpciones.setVisible(false);
        lblArchivo.setVisible(false);
        lblAnalisis.setVisible(false);
        lblNombre.setVisible(false);
        btnOK.setVisible(false);
        btnImpresora.setVisible(false);
        btnInsumos.setVisible(false);
        btnNoReparados.setVisible(false);
        btnIngresos.setVisible(false);
        btnEgresos.setVisible(false);
        Warning.setVisible(false);
        btnArchivo.setBorderPainted(false);
        btnAnalisis.setBorderPainted(false);
        btnServicios.setBorderPainted(false);
        btnOpciones.setBorderPainted(false); 
        Bandera.setVisible(true);
        Brothernologic.setVisible(true);
        txtCodRecibo.setVisible(false);
        lblCodRecibo.setVisible(false);
        btnIrFactura.setVisible(false);
        btnAceptarCod.setVisible(false);
        btnBuscarRecibo.setVisible(false);
        lblConsultaCliente.setVisible(false);
        lblConsultaRecibo.setVisible(false);
        lblEstadoRecibo.setVisible(false);
        btnCerrarSesion.setVisible(false);
        btnAyuda.setVisible(false);
        btnEstatus.setVisible(false);
    }//GEN-LAST:event_btnIrFacturaActionPerformed

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
Inicio i=new Inicio();

        i.setResizable(false);
        i.setLocationRelativeTo(null);
        i.setVisible(true);
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnEstatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstatusActionPerformed
      Estatus es=new Estatus();

        es.setResizable(false);
        es.setLocationRelativeTo(null);
        es.setVisible(true);  // TODO add your handling code here:
    }//GEN-LAST:event_btnEstatusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bandera;
    private javax.swing.JLabel Brothernologic;
    private javax.swing.JButton Cerrar;
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton Minimizar;
    private javax.swing.JLabel Nombre;
    private javax.swing.JLabel Usuario;
    private javax.swing.JLabel Warning;
    private javax.swing.JButton btnAceptarCod;
    private javax.swing.JButton btnAcerca;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnAnalisis;
    private javax.swing.JButton btnArchivo;
    private javax.swing.JButton btnAyuda;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnBuscarRecibo;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnComputadora;
    private javax.swing.JButton btnEgresos;
    private javax.swing.JButton btnEstatus;
    private javax.swing.JButton btnImpresora;
    private javax.swing.JButton btnIngresos;
    private javax.swing.JButton btnInsumos;
    private javax.swing.JButton btnIrFactura;
    private javax.swing.JButton btnNoReparados;
    private javax.swing.JButton btnOK;
    private javax.swing.JButton btnOpciones;
    private javax.swing.JButton btnPresupuesto;
    private javax.swing.JButton btnServicios;
    private javax.swing.JButton btnTelefono;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblAnalisis;
    private javax.swing.JLabel lblArchivo;
    private javax.swing.JLabel lblCedula;
    private javax.swing.JLabel lblCodRecibo;
    private javax.swing.JLabel lblConsultaCliente;
    private javax.swing.JLabel lblConsultaRecibo;
    private javax.swing.JLabel lblEstadoRecibo;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblOpciones;
    private javax.swing.JLabel lblServicio;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtCodRecibo;
    // End of variables declaration//GEN-END:variables
}
